// Generated by https://quicktype.io

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  project: string;
  projectDescription: string;
  designation: string;
}
